# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ClientMessage_

class MessageUnion(object):
    NONE = 0
    foxglove_websocket_v1_Subscribe = 1
    foxglove_websocket_v1_Unsubscribe = 2

