# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Subscribe_

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Subscription(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Subscription()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubscription(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Subscription
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Subscription
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Subscription
    def ChannelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(2)
def SubscriptionStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddId(builder, id): builder.PrependUint32Slot(0, id, 0)
def SubscriptionAddId(builder, id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, id)
def AddChannelId(builder, channelId): builder.PrependUint32Slot(1, channelId, 0)
def SubscriptionAddChannelId(builder, channelId):
    """This method is deprecated. Please switch to AddChannelId."""
    return AddChannelId(builder, channelId)
def End(builder): return builder.EndObject()
def SubscriptionEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)