# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Advertise(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Advertise()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAdvertise(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Advertise
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Advertise
    def Channels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from foxglove.websocket.v1.Advertise_.Channel import Channel
            obj = Channel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Advertise
    def ChannelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Advertise
    def ChannelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def AdvertiseStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddChannels(builder, channels): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(channels), 0)
def AdvertiseAddChannels(builder, channels):
    """This method is deprecated. Please switch to AddChannels."""
    return AddChannels(builder, channels)
def StartChannelsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AdvertiseStartChannelsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartChannelsVector(builder, numElems)
def End(builder): return builder.EndObject()
def AdvertiseEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)