# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Subscribe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Subscribe()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubscribe(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Subscribe
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Subscribe
    def Subscriptions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from foxglove.websocket.v1.Subscribe_.Subscription import Subscription
            obj = Subscription()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Subscribe
    def SubscriptionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Subscribe
    def SubscriptionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def SubscribeStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSubscriptions(builder, subscriptions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(subscriptions), 0)
def SubscribeAddSubscriptions(builder, subscriptions):
    """This method is deprecated. Please switch to AddSubscriptions."""
    return AddSubscriptions(builder, subscriptions)
def StartSubscriptionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SubscribeStartSubscriptionsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartSubscriptionsVector(builder, numElems)
def End(builder): return builder.EndObject()
def SubscribeEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)