# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Unsubscribe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Unsubscribe()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnsubscribe(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Unsubscribe
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Unsubscribe
    def SubscriptionIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Unsubscribe
    def SubscriptionIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Unsubscribe
    def SubscriptionIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Unsubscribe
    def SubscriptionIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def UnsubscribeStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSubscriptionIds(builder, subscriptionIds): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(subscriptionIds), 0)
def UnsubscribeAddSubscriptionIds(builder, subscriptionIds):
    """This method is deprecated. Please switch to AddSubscriptionIds."""
    return AddSubscriptionIds(builder, subscriptionIds)
def StartSubscriptionIdsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def UnsubscribeStartSubscriptionIdsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartSubscriptionIdsVector(builder, numElems)
def End(builder): return builder.EndObject()
def UnsubscribeEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)