# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ServerMessage_

class MessageUnion(object):
    NONE = 0
    foxglove_websocket_v1_ServerInfo = 1
    foxglove_websocket_v1_StatusMessage = 2
    foxglove_websocket_v1_Advertise = 3
    foxglove_websocket_v1_Unadvertise = 4
    foxglove_websocket_v1_MessageData = 5

